source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
#gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem "nested_form"
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
gem 'multi-select-rails'
gem 'kaminari'
gem 'bootstrap-editable-rails'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'smarter_csv'
gem 'activerecord-import'
#gem 'sidekiq'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'paperclip'
gem 'execjs'
gem 'therubyracer'
gem 'validate_url'
gem 'activemerchant', :require => 'active_merchant'
gem 'offsite_payments'
gem 'country_select', github: 'stefanpenner/country_select'
gem 'rest-client'
gem 'pundit'
gem "paranoia", "~> 2.0"
gem 'unicorn'
gem 'city-state'
gem 'exception_notification'
gem 'acts_as_list'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'spreadsheet'
gem 'activerecord-session_store', github: 'rails/activerecord-session_store'
gem 'jwt'
gem 'zendesk_api'
gem 'ruby-bandwidth'
gem 'devise_masquerade'
gem 'recaptcha', require: 'recaptcha/rails'
gem 's3', '~> 0.3.24'
gem 'mongoid', '~> 5.1.0'
gem 'plivo'
gem 'twilio-ruby'

group :development, :test do
  gem 'quiet_assets'
  gem 'thin'
  #gem 'spring'
  gem 'minitest'
  #gem 'capistrano', '3.1.0'
  #gem 'capistrano-rails'
  #gem 'capistrano-rvm'
  #gem 'capistrano-bundler'
  #gem 'simplecov'
  #gem 'simplecov-rcov'
  #gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'api_matchers'
  #gem 'pry'
  #gem 'pry-remote'
  #gem 'pry-rails'
  #gem 'pry-stack_explorer'
  #gem 'pry-byebug'
end

